API/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('coupon/', views.api_coupon),
    path('coupon/<int:pk>/create/', views.api_create_coupon),
    path('coupon/<int:pk>/delete/', views.api_delete_coupon),
    path('coupon/<int:pk>/change/', views.api_change_coupon),
    path('coupon/<int:pk>/view/', views.api_view_coupon),


    path('order/<int:pk>/create/', views.api_create_order),
    path('order/<int:pk>/delete/', views.api_delete_order),
    path('order/<int:pk>/change/', views.api_change_order),
    path('order/<int:pk>/view/', views.api_view_order),

    path('user/create/',views.api_create_coupon),
    path('user/dekete/', views.api_delete_coupon),
    path('user/change/',views.api_change_coupon),
    path('user/view/',views.api_view_coupon),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Auth/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.MainView.as_view()),
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.login_view, name='login'),
    path('logout', views.logoutView, name='logout'),
]

Cart/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('', views.cart_detail, name ='detail'),
    path('add/<int:pk>', views.cart_add, name ='add'),
    path('remove/<int:pk>', views.cart_remove, name='remove'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coupon/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('active/', views.coupon_apply, name ='apply'),
    path('create/',views.coupon_create_game, name='create_game'),
    path('search/',views.SearchCoupon, name="search"),
    path('searchbot/',views.SearchCouponBot, name="searchbot"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import include


urlpatterns = [
    path('', views.index),
    path('product/', views.ProductsViews.as_view(), name = 'Products'), 
    path('product/<int:pk>/', views.ProductsDetailView.as_view(), name = 'product_detail'),
    path('product/<int:pk>/create_comment/', views.Create),
    path('lol/', views.test, name = "test"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('searchbot/', views.SearchCouponBot, name='searchbot'),
    path('searchbot/detail/', views.order_detail, name='order_detail'),
    path('admin/order/<order_id>)/', views.admin_order_detail, name='admin_order_detail'),
    
]

cpu/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Main import views


urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(('API.urls', 'API'),namespace='API')),
    path('admin/', admin.site.urls),
    path('cart/', include(('Cart.urls', 'Cart'), namespace='Cart')),
    path('main/', include(('Main.urls', 'Main'), namespace='Main')),
    path('orders/', include(('Order.urls', 'Order'), namespace='Orders')),
    path('userauth/', include(('Auth.urls', 'Auth'), namespace='Auth')),
    path('profile/', include(('Profile.urls', 'Profile'),namespace='Profile')),
    path('feedback/', include(('Feedback.urls', 'Feedback'),namespace='Feedback')),
    path('bnc/', include(('Game.urls', 'Game'),namespace='Game')),
    path('coupon/', include(('Coupon.urls', 'Coupon'),namespace='Coupon')),
    path('tg/', include(('Telegramm.urls', 'Telegramm'),namespace='Telegramm')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models
from django.contrib.auth import login, logout, authenticate
from Main.models import Product
from django.contrib.auth import get_user_model



class Cart(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='basket')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(
        verbose_name='количество', default=0)
    datetime = models.DateTimeField(
        verbose_name='время', auto_now_add=True)
    
# Create your models here.

Cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Main.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from Coupon.forms import CouponApplyForm

@require_POST
def cart_add(request, pk):
    print("SALAM", pk)
    cart = Cart(request)
    print
    id = pk
    print(id)
    product = get_object_or_404(Product, pk=pk)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('Cart:detail')

def cart_remove(request, pk):
    print("HELLO", pk)
    cart = Cart(request)
    product = get_object_or_404(Product, pk=pk)
    cart.remove(product)
    return redirect('Cart:detail')
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                            initial={'quantity': item['quantity'],
                            'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'Cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   })

Cart/templates/Cart/cart.html
{% extends 'base_generic.html'%}
{%block content%}
<form actions="" method="post">{% csrf_token %}
        <div class="form-group">
          {{form.as_p}}<br>
</form>
<button type="submit" class="btn btn-warning">Войти</button><br>
{%endblock%}

Cart/templates/Cart/detail.html
{% extends "base_generic.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<br><h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.logo %}
                                    {{ product.logo.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}" style="width:50px;height:50px;">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'Cart:remove' product.id %}">Remove </a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr><br>
            {% endwith %}
        {% endfor %}
        {% if cart.coupon %}
    <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
    <tr>
        <td>
            "{{ cart.coupon.code }}" coupon
            ({{ cart.coupon.discount }}% off)
        </td>
        <td colspan="4"></td>
        <td class="num neg">
            - ${{ cart.get_discount|floatformat:"2" }}
        </td>
    </tr>
{% endif %}
<tr class="total">
    <td>Total</td>
    <td colspan="4"></td>
    <td class="num">
        ${{ cart.get_total_price_after_discount|floatformat:"2" }}
    </td>
</tr>
        </tbody>
    </table>
    <form action="{% url 'Coupon:apply' %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
    {%if user.is_authenticated%}
    
        <a href="{% url 'Main:Products' %}"><button class="btn btn-primary btn-lg active" type="button">Continue shopping</button></a>
        <a href="{% url 'Orders:order_create' %}"><button class="btn btn-primary btn-lg active" type="button">Order now!</button></a>
    {%else%}    
        <h1>Are u logged?</h1>
        <a href="{% url 'Auth:register'%}"><button class="btn btn-primary btn-lg active" type="button">Register Now!</button></a>
        <a href="{%url 'Auth:login' %}"><button class="btn btn-primary btn-lg active" type="button">Login now!</button></a>
        </a>
    {%endif%}
    </p>
{% endblock %}