API/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('coupon/', views.api_coupon),
    path('coupon/<int:pk>/create/', views.api_create_coupon),
    path('coupon/<int:pk>/delete/', views.api_delete_coupon),
    path('coupon/<int:pk>/change/', views.api_change_coupon),
    path('coupon/<int:pk>/view/', views.api_view_coupon),


    path('order/<int:pk>/create/', views.api_create_order),
    path('order/<int:pk>/delete/', views.api_delete_order),
    path('order/<int:pk>/change/', views.api_change_order),
    path('order/<int:pk>/view/', views.api_view_order),

    path('user/create/',views.api_create_coupon),
    path('user/dekete/', views.api_delete_coupon),
    path('user/change/',views.api_change_coupon),
    path('user/view/',views.api_view_coupon),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Coupon/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('active/', views.coupon_apply, name ='apply'),
    path('create/',views.coupon_create_game, name='create_game'),
    path('search/',views.SearchCoupon, name="search"),
    path('searchbot/',views.SearchCouponBot, name="searchbot"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Game/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Game import views
from .views import BNC, check, get_csrf


urlpatterns = [
    path('', views.StartGame, name='start'),
    path('game/', views.BNC, name='game'),
    path('check/',views.check_out, name='check'),
    path('getcsrf/', views.get_csrf, name = 'csrf'),
    path('win/', views.win, name='win'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cpu/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Main import views


urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(('API.urls', 'API'),namespace='API')),
    path('admin/', admin.site.urls),
    path('cart/', include(('Cart.urls', 'Cart'), namespace='Cart')),
    path('main/', include(('Main.urls', 'Main'), namespace='Main')),
    path('orders/', include(('Order.urls', 'Order'), namespace='Orders')),
    path('userauth/', include(('Auth.urls', 'Auth'), namespace='Auth')),
    path('profile/', include(('Profile.urls', 'Profile'),namespace='Profile')),
    path('feedback/', include(('Feedback.urls', 'Feedback'),namespace='Feedback')),
    path('bnc/', include(('Game.urls', 'Game'),namespace='Game')),
    path('coupon/', include(('Coupon.urls', 'Coupon'),namespace='Coupon')),
    path('tg/', include(('Telegramm.urls', 'Telegramm'),namespace='Telegramm')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Game/models.py
from django.db import models

# Create your models here.

Game/forms.py
from django import forms
from Feedback.tasks import send_feedback_email_task

class GameForm(forms.Form):
    input = forms.CharField(label="Input", widget=forms.Textarea(attrs={'class': 'text-field__input',
                'placeholder': 'input', 'id':'input-field',

                }),max_length=4, min_length=4)

Game/views.py
from django.shortcuts import render, redirect
from .App import insert, answer, check
from django.conf import settings
from .forms import GameForm
from random import randint
from django.http import HttpRequest
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
import django.middleware.csrf
from rest_framework.response import Response
from rest_framework.views import APIView
import requests
# Create your views here.
@api_view(['GET'])
@permission_classes((permissions.AllowAny,))
def get_csrf(request):
    csrf = django.middleware.csrf.get_token(request)
    print(csrf)
    return Response({"result": csrf}, status=status.HTTP_200_OK)


def StartGame(request):
 
    ans = answer()
    Ntry = 4
    ansbox = list()
    request.session['ansbox'] = ansbox
    request.session['ans'] = ans
    request.session['Ntry'] = Ntry

    return render(request, 'startgame.html')


@api_view(['POST'])
@permission_classes((permissions.AllowAny,))
def check_out(request):
    data = request.data
    var1_list = insert(data['input'])
    var1 = data['input']
    s = request.session
    Ntry = s['Ntry']
    ans = s['ans']
    result = check(ans, var1)
    request.session['Ntry'] = Ntry - 1
    place = result[0]
    all = result[1]
    print(Ntry)  
    return Response({"result": var1, 'place':place, 'all':all, 'Ntry':Ntry}, status=status.HTTP_200_OK)

def win(request):
    text = "check ur telegramm for coupon!"
    return render(request, 'win.html', {'text':text})




def BNC(request: HttpRequest):
    ####    VARS
    place = 0
    all = 0
    s = request.session     #присваиваем сессионый запрос

    ans = s.get('ans')      #вытаскиваем ответ
    print(ans)
    ansbox = s.get('ansbox')
    Ntry = s.get('Ntry')    #вытаскиваем попытки
    print(Ntry)


    
    text = "Play to BnC and get a cupon to 20% SALE!"
    

    if request.method == 'POST':
        if Ntry > 1:
            Ntry = Ntry - 1                          ### увеличиваем счетчик
            request.session['Ntry'] = Ntry          ### присваиваем в сессию счетчик
            s = request.session 
            
            var1 = request.POST.get('input')
            user = request.user
            data = {'input': var1}
            print(data)
            form = GameForm(data)
            if form.is_valid():
                var1 = insert(var1)
                result = check(ans, var1)
                place = result[0]
                all = result[1]
                game = {'var1':var1,
                        'place':place,
                        'all':all,}
                ansbox.append(game)

                for i in range(len(ansbox)):
                    a = ansbox[i]
                    print(a)
                    
                ansbox[9-Ntry]
                if result == [4, 4]:
                    Ntry = str(Ntry)
                    user = request.user.username
                    #print(s.items())
                    hash = s.get('_auth_user_hash')[:5]
                    text = "check ur telegramm for coupon!"
                    return render(request, 'win.html', {'text':text})
            else:
                error = 'INCORRECT'
        else:
            text = "SOSI UEBISHE LOL"
            
            print(text)
            return render(request, 'gameover.html')
    form = GameForm
    context = {
        'text' : text,
        'form' : form,
        'ans' : ans,
        'Ntry': Ntry,
        'Place': place,
        'All': all,
        }
    return render(request, 'game.html', context)

Game/templates/game copy.html
{%extends base_generic.html%}

Game/templates/game.html
{%extends 'base_generic.html'%}
{%block content%}
<div class="Game">
    
    <div class="Game-answer">
        <textarea id="Game-answer" readonly="True" style="margin: 10px; width: 90%; height: 90%; border-radius: 15px; background-color: rgba(5, 44, 20, 0.74); font-size: 11px; font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; text-decoration-color: blue;"></textarea>
    
    </div>
    <div class="game-form"> 
        
        <div class="game-out">
            <p>{{text}}</p> <br>
        
            {% if user.is_superuser == True %}
            {{ans}}<br> 
            {% endif %}
            <textarea id="Ntry" style="border-radius: 40px; font-size: 30px; text-align: center; max-width: 60px; max-height: 54px; font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif">5</textarea>
        </div>

        <div class="game-in">
            <input class ="text-field__input" type="text" placeholder="Пиши сюда уебище", id="input_field">
        </div>

        <div class="game-button">
            <button class="btn btn-success" type="submit" id="btn-ok">Тык</button>

            {% csrf_token %}
            <script var token = {%csrf_token%}></script>
            {% load static %}
            <script  src="{% static 'input.js' %}"></script>

        </div>
        
        
    </div>
   
</div>
{%endblock%}

Game/templates/gameover.html
{%extends 'base_generic.html'%}
{%block content%}
<div class="Game">
        <div class="game-out">
           You lose( Try again)
        </div>


        <div class="game-button">
            <a href="{%url 'Game:start'%}"><button class="btn btn-primary btn-lg active" type="button">Play for sale</button></a><br>
        </div>
    </form>
</div>
{%endblock%}

Game/templates/startgame.html
{%extends 'base_generic.html'%}
{%block content%}
<div class="Game">
        <div class="game-out">
            Now you can play with me and get cupon for 20% sale
        </div>


        <div class="game-button">
            <a href="{%url 'Game:game'%}"><button class="btn btn-primary btn-lg active" type="button">Play for sale</button></a><br>
        </div>
    </form>
</div>
{%endblock%}

Game/templates/win.html
{%extends 'base_generic.html'%}
{%block content%}
<div class="Game">
        <div class="game-out">
           !You Win!
        

        <div class="game-in">
            <div class="coupon">
                Your coupon is = {{text}}
                
                </div>
        </div>
    </div>
        <div class="game-button">
            <form action="{% url 'Coupon:create_game' %}" method="post">
                <input type="submit" value="Apply"><br>
                {% csrf_token %}
            </form>
        </div>
    </form>
</div>
{%endblock%}