API/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('coupon/', views.api_coupon),
    path('coupon/<int:pk>/create/', views.api_create_coupon),
    path('coupon/<int:pk>/delete/', views.api_delete_coupon),
    path('coupon/<int:pk>/change/', views.api_change_coupon),
    path('coupon/<int:pk>/view/', views.api_view_coupon),


    path('order/<int:pk>/create/', views.api_create_order),
    path('order/<int:pk>/delete/', views.api_delete_order),
    path('order/<int:pk>/change/', views.api_change_order),
    path('order/<int:pk>/view/', views.api_view_order),

    path('user/create/',views.api_create_coupon),
    path('user/dekete/', views.api_delete_coupon),
    path('user/change/',views.api_change_coupon),
    path('user/view/',views.api_view_coupon),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('', views.cart_detail, name ='detail'),
    path('add/<int:pk>', views.cart_add, name ='add'),
    path('remove/<int:pk>', views.cart_remove, name='remove'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Game/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Game import views
from .views import BNC, check, get_csrf


urlpatterns = [
    path('', views.StartGame, name='start'),
    path('game/', views.BNC, name='game'),
    path('check/',views.check_out, name='check'),
    path('getcsrf/', views.get_csrf, name = 'csrf'),
    path('win/', views.win, name='win'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import include


urlpatterns = [
    path('', views.index),
    path('product/', views.ProductsViews.as_view(), name = 'Products'), 
    path('product/<int:pk>/', views.ProductsDetailView.as_view(), name = 'product_detail'),
    path('product/<int:pk>/create_comment/', views.Create),
    path('lol/', views.test, name = "test"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('searchbot/', views.SearchCouponBot, name='searchbot'),
    path('searchbot/detail/', views.order_detail, name='order_detail'),
    path('admin/order/<order_id>)/', views.admin_order_detail, name='admin_order_detail'),
    
]

cpu/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Main import views


urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(('API.urls', 'API'),namespace='API')),
    path('admin/', admin.site.urls),
    path('cart/', include(('Cart.urls', 'Cart'), namespace='Cart')),
    path('main/', include(('Main.urls', 'Main'), namespace='Main')),
    path('orders/', include(('Order.urls', 'Order'), namespace='Orders')),
    path('userauth/', include(('Auth.urls', 'Auth'), namespace='Auth')),
    path('profile/', include(('Profile.urls', 'Profile'),namespace='Profile')),
    path('feedback/', include(('Feedback.urls', 'Feedback'),namespace='Feedback')),
    path('bnc/', include(('Game.urls', 'Game'),namespace='Game')),
    path('coupon/', include(('Coupon.urls', 'Coupon'),namespace='Coupon')),
    path('tg/', include(('Telegramm.urls', 'Telegramm'),namespace='Telegramm')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_generic.html
<!DOCTYPE html>

<html lang="en">
<head>
  <title>{% block title%}{%endblock%}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
</head>
<header>
<!-- Background image -->
<div
  class="p-5 text-center bg-image"
  style="
      background-image: url('../../static/images/kari-shea-1SAnrIxw5OY-unsplash.jpg');
      background-size: auto 240px;
    
      height: 240px;
      
    "

>
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <h1 class="mb-3">CPU-shOp</h1>
        <h4 class="mb-3">Есть какие-то вопросы?)</h4>
        <a class="btn btn-outline-light btn-lg" href="{% url 'Feedback:main' %}" role="button">Просто спросите</a>
        <div class="auth">
          {%if user.is_authenticated%}
          <a href="/userauth/logout"><button class="btn btn-outline-light btn-lg" style="float:left" type="button">Выйти ({{user.username}})</button></a>
            {% if user.is_superuser == True %}
          <a href="/admin/">AdminPanel<br></a>  
            {% endif %}
          {%else%}
          <a href="/userauth/"><button class="btn btn-outline-light btn-lg" style="float:left;" type="button">Вход</button></a>
          {%endif%}
        </div>
        
      </div>
    </div>
  </div>
</div>
<!-- Background image -->
</header>

<body>
<div class = background>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
         <class="sidebar-nav">
          
          <br>
          <img src = "url('../../../media/logo.jpg" style="width:100%;height:auto;border-radius:30px; border: 10px; flex: auto;"></li><br>
          <a href="{%url 'Telegramm:activate'%}"><button class="butntg-ico" style=" background-image: url('/media/png-transparent-telegram-icon-telegram-logo-computer-icons-telegram-blue-angle-triangle-thumbnail.png'); background-size:cover;  border-radius: 500px;   width: auto;   height: auto; size: auto; margin-top: 5px;"  type="button"></button></a></li><br>
      
            <a href="{% url 'index' %}"><button type="button" style="border-radius: 0px 100px 0px 0px;" class="btn-menu-nav">Главная</button></a>
            <a href="{% url 'Main:Products' %}"><button type="button" class="btn-menu-nav">Каталог</button></a>
            <a href="{% url 'Order:order_create'%}"><button type="button" class="btn-menu-nav">Заказать</button></a>
            <a href="{% url 'Cart:detail' %}"><button type="button" class="btn-menu-nav">Корзина</button></a>
            <a href="{%url 'Game:start'%}"><button class="btn-menu-nav"  style=" border-radius: 0px 0px 30px 100px; "> <type="button">Сыграй</button></a>
            
       
          <hr> 
          
        
     {% endblock %}
      

      </div>
        
        <div class="col-sm-10 ">{% block content %}{% endblock %}<br>
        
        </div>
        
        
        
      
  </div>
</div>
</body>




<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">

  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">

      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            LOOK US ON PORNHUB.COM 
          </p>
        </div>
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

          <h6 class="text-uppercase fw-bold mb-4">
            We here:
          </h6>
          <p>
            <a href="#!" class="text-reset">CPU</a>
          </p>
          <p>
            <a href="#!" class="text-reset">PHONE</a>
          </p>
          <p>
            <a href="#!" class="text-reset">TV</a>
          </p>
        </div>
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="{% url 'Profile:main'%}" class="text-reset">Profile</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> Selo Zalupipo D.C. , 666666, Russia</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            dumbquestion@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 8800 555 35 35</p>
          <p><i class="fas fa-print me-3"></i> + 8999 148 82 28</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.089);">
    © 2023 Copyright: Really?
  </div>
  <!-- Copyright -->
</footer>
</html>