API/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('coupon/', views.api_coupon),
    path('coupon/<int:pk>/create/', views.api_create_coupon),
    path('coupon/<int:pk>/delete/', views.api_delete_coupon),
    path('coupon/<int:pk>/change/', views.api_change_coupon),
    path('coupon/<int:pk>/view/', views.api_view_coupon),


    path('order/<int:pk>/create/', views.api_create_order),
    path('order/<int:pk>/delete/', views.api_delete_order),
    path('order/<int:pk>/change/', views.api_change_order),
    path('order/<int:pk>/view/', views.api_view_order),

    path('user/create/',views.api_create_coupon),
    path('user/dekete/', views.api_delete_coupon),
    path('user/change/',views.api_change_coupon),
    path('user/view/',views.api_view_coupon),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from . import views


urlpatterns = [
    path('', views.cart_detail, name ='detail'),
    path('add/<int:pk>', views.cart_add, name ='add'),
    path('remove/<int:pk>', views.cart_remove, name='remove'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import include


urlpatterns = [
    path('', views.index),
    path('product/', views.ProductsViews.as_view(), name = 'Products'), 
    path('product/<int:pk>/', views.ProductsDetailView.as_view(), name = 'product_detail'),
    path('product/<int:pk>/create_comment/', views.Create),
    path('lol/', views.test, name = "test"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cpu/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import include, re_path
from django.conf.urls.static import static

from django.conf import settings

from Main import views


urlpatterns = [
    path('', views.index, name='index'),
    path('api/', include(('API.urls', 'API'),namespace='API')),
    path('admin/', admin.site.urls),
    path('cart/', include(('Cart.urls', 'Cart'), namespace='Cart')),
    path('main/', include(('Main.urls', 'Main'), namespace='Main')),
    path('orders/', include(('Order.urls', 'Order'), namespace='Orders')),
    path('userauth/', include(('Auth.urls', 'Auth'), namespace='Auth')),
    path('profile/', include(('Profile.urls', 'Profile'),namespace='Profile')),
    path('feedback/', include(('Feedback.urls', 'Feedback'),namespace='Feedback')),
    path('bnc/', include(('Game.urls', 'Game'),namespace='Game')),
    path('coupon/', include(('Coupon.urls', 'Coupon'),namespace='Coupon')),
    path('tg/', include(('Telegramm.urls', 'Telegramm'),namespace='Telegramm')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/models.py
from django.db import models
from taggit.managers import TaggableManager


class Product(models.Model):
    logo = models.ImageField(upload_to='media')
    category = models.CharField(max_length=50, null = True)
    VC = models.IntegerField()
    name = models.CharField(max_length=256)
    description = models.TextField(max_length=4096)
    price = models.FloatField()
    tags = TaggableManager()
    def __str__(self):
      
        return self.name
        
    def get_absolute_url(self):
        return f'{self.pk}/'

class Comment(models.Model):
    title = models.TextField(max_length=2048)
    PrProd = models.ForeignKey('Product', on_delete = models.CASCADE, null=True)
    PrUser = models.ForeignKey('auth.user', on_delete = models.CASCADE, null = True) 
    def __str__(self):
      
        return self.title
        

class Order(models.Model):
    prname = models.ForeignKey('Product', on_delete = models.CASCADE, null = True)
    






Main/forms.py
from .models import Comment, Product
from django.forms import ModelForm, TextInput, Textarea
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.contrib.auth import login, logout, authenticate

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'PrProd', 'PrUser']
        

        widgets = {
            
            "title": Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Put ur Comm',
            })
         
        }


Main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, request
from django.views import generic
from django.contrib import sessions
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag

from .models import Product
from .models import Comment
from .forms import CommentForm
from Cart.forms import CartAddProductForm
from Coupon.forms import CouponSearchForm
import time



class ProductsViews(generic.ListView):
    model = Product
    paginate_by = 9
    tag = None
    def tag(request, tag_slug=None):
        if tag_slug:
            tag =  get_object_or_404(Tag, slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])
        return(request, tag, object_list)
    context_object_name = 'Products'
    queryset = Product.objects.all()
    template_name = 'Products/my_products_list.html'
    def get_contex_data(self, **kwargs):

        context = super(ProductsViews, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context

   
class ProductsDetailView(generic.DetailView):
    model = Product
    context_object_name = 'Product'
    template_name = 'Products/prod.html'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = kwargs['object'].pk
        comments = Comment.objects.filter(PrProd = pk)
        cart_product_form = CartAddProductForm()
        context['comments'] = comments
        context['cart_form'] = cart_product_form
        return context
    
    def get_cart_data(self, pk):
        cart_product_form = CartAddProductForm()
    
def Create(request, pk, **kwargs):
    
    user = request.user
    print(user)
    
    error = ''
    form = CommentForm
    if request.method == 'POST':
        product = Product.objects.get(pk=pk)
        user = request.user
        title = request.POST.get('title')
        data = {'title': title, 'PrProd': product, 'PrUser': user}
        form = CommentForm(data)
        if form.is_valid():
            form.save()
            print(pk)
            return redirect('/main/product/')
        else:
            error = 'INCORRECT'
            print(form)

    data  = {
        'PrProd': pk,
        'PrUser' : user,
        'form' : form,
        'error' : error,
    }
    print(data)
    return render(request, 'Products/create_comment.html', data)


      
def index(request):
    form_search = CouponSearchForm
    num_pr = Product.objects.all().count()
    context = {
        'num_pr': num_pr,
        'form_search':form_search,
    }
    
    return render(request, 'main/index.html', context=context)

def test(request):
    if request.method == 'GET':
            s = request.session
            print(s.keys())
            print(s.items())
            render(request, 'base_generic.html')
            if request.method == 'POST':
                return render(request, 'base_generic.html')
            
                

    return render(request, 'base_generic.html')
    

# Create your views here.

Main/templates/Products/create_comment.html
{% extends 'base_generic.html'%}

{% block content %}
<dir><main><h1>Input ur text-comment here:</h1></main></dir>
<dir>

   {% load static %}  

    <form method="post">
            {% csrf_token %}
           
            {{ form.title }}<br>
            
            <span>{{ error }}</span>
        
        <button class="btn btn-success" type="submit">ENTER</button>

 
    </form>
</dir>
{% endblock %}

Main/templates/Products/my_products_list.html
{% extends 'base_generic.html'%}
{% block content %}
<div class="product-state">
  <h1 sd>Products state</h1>
  {% if Products %}
</div>  
<div class="Product_list">
    {% for product in Products %}
          <div class="product-wrap">
            <div class="product-item">
              <img src="
              {% if product.logo %}
                  {{ product.logo.url }}
              {% else %}
                  
              {% endif %}" style="width: 240px;height:240px;"> 
              <div class="product-buttons">
                <a href="{{product.get_absolute_url}}" class="button">Заказать</a>
              </div>
            </div>
            <div class="product-title">
              <a href="{{product.get_absolute_url}}">{{product.name}}</a>
              <span class="product-price">₽ {{product.price}}</span>
            </div>
          </div>
    {% endfor %}
</div> 
  {% else %}
  <h1>NOTHING</h1>
  {% endif %}
  {% if is_paginated %}
    <div class="pagination" style="position: static">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                 
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
          
    </div>

  {% endif %}
 
  {% endblock %}
{%block title%}

    CPU-shOp

{%endblock%}

Main/templates/Products/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

Main/templates/Products/prod.html
{% extends 'base_generic.html'%}
{%block content%}
    <ul>
            <main>     
            <h1>{{Product.name}}</h1></li>
            <div class="tag">
                <p class="tags">Category | {{ Product.tags.all|join:", " }}</p>
            </div>
            {{Product.description}}</li><br>
            <h1>{{Product.price}}</h1>
                
            <img src = "{{Product.logo.url}}" style="width:200px;height:200px;border-radius:30px;" >  
            <form action="{% url 'Cart:add' pk=Product.id%}" method="post">
                {{ cart_form }}
                {{pk}}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mb-2">Add to cart</button>
            </form>
        </main> 
    </ul>
    
    {% if comments %}
        {%for comment in comments%}
        <div class="alert alert-dark">
            <hr> 
            <section> <h6>{{comment.PrUser}}</h3>
            <div class="alert alert-warning">
                <p>{{comment.title}}</p>
            </div>
            </section>
        </div>      
        {%endfor%}
    {% else %}
    <div class="alert alert-warning">
        <p><b>NOTHING</b></p>        
    </div>
    {% endif %}
    {%if user.is_authenticated%}
        <a href="create_comment/"><button type="button" class="btn btn-lg btn-primary" disabled>Create comment</button>
    {%else%}
        <a href="/userauth/login/"><button type="button" class="btn btn-secondary btn-lg disabled" disabled>Login to Comment</button></a>
    {%endif%}

{%endblock%}




  